#!/bin/bash

# flashing the img
HOSTNAME="pi-baker"
SSID="***REMOVED***"
PASS="***REMOVED***"

./flash --hostname $HOSTNAME --ssid $SSID --password $PASS --als boot/als.sh --bootconf boot/config.txt --userdata boot/user-data $(ls | grep hypriotos.*.zip)
