#!/bin/bash

# flashing the img
HOSTNAME="pi-baker"
SSID="***REMOVED***"
PASS="***REMOVED***"

./flash --bootconf boot/config.txt --userdata boot/user-data --hostname $HOSTNAME --ssid $SSID --password $PASS $(ls | grep hypriotos.*.zip)
