#!/bin/bash
# Configs
declare USER="lucy" #as defined in boot/user-data

declare LEADER="mission" #as defined in built scripts

declare -a formation=(
    "mission" 
    "excelsior" "clarion"
    "balmy" "geary"
    "divisadero" "valencia"
)

declare -a managers=(
	"divisadero" "valencia"
)

declare -a workers=(
    "excelsior" "clarion"
    "balmy" "geary"
)
