#!/bin/bash
# Configs
declare USER="lucy" #as defined in boot/user-data

declare LEADER="mission.local" #as defined in built scripts

declare -a formation=(
    "mission.local" 
    "excelsior.local" "clarion.local"
    "balmy.local" "geary.local"
    "divisadero.local" "valencia.local"
)

declare -a managers=(
	"divisadero.local" "valencia.local"
)

declare -a workers=(
    "excelsior.local" "clarion.local"
    "balmy.local" "geary.local"
)
