#!/bin/bash
# getting swarm config
my_dir="$(dirname "$0")"
source "$my_dir/swarm-config"

# Can only run on manager nodes!
info() {
	docker node ls -q | xargs docker node inspect \
	  -f '{{ .ID }} [{{ .Description.Hostname }}]: {{ .Description.Platform }}
	  NanoCPUs={{ .Description.Resources.NanoCPUs  }} | MemoryBytes={{ .Description.Resources.MemoryBytes  }}
	  leader? {{ .ManagerStatus }}
	  {{ .Spec.Role }} {{ .Spec.Availability }} @{{ .Status.Addr }} state={{ .Status.State }}
	  {{ .Spec.Labels }}
	  '
	  
	docker service ps $(docker service ls -q) --filter "desired-state=Running"
}

ssh $USER@$LEADER "$(declare -f info); info"

# TODO
# https://medium.com/@iaincollins/how-to-run-a-command-on-every-node-in-a-docker-swarm-cluster-60b7f398d1ec
