#!/bin/bash
# Configs
declare USER="lucy" #as defined in boot/user-data

declare LEADER="kubepileader.local" #as defined in built scripts

declare -a formation=(
    "kubepileader.local" 
    "kubepi001.local" "kubepi002.local"
    "kubepi003.local" "kubepi004.local"
    "kubepi-x.local" "kubepi-y.local"
)

declare -a managers=(
	"kubepi-x.local" "kubepi-y.local"
)

declare -a workers=(
    "kubepi001.local" "kubepi002.local"
    "kubepi003.local" "kubepi004.local"
)
