#!/bin/bash
#
# getting swarm config
my_dir="$(dirname "$0")"
source "$my_dir/swarm-config"

#####################
is_alive_ping() {
	local f_host=$1
	ping -c 1 $f_host > /dev/null
	if [ $? -eq 0 ]; then
		echo "$f_host is UP"
		return 0
	fi
	
	echo "$f_host is DOWN"
	return 1
}

check_hosts() {
	for node in "${formation[@]}"; do
		is_alive_ping "${node}"
	done
}

check_hosts
