#!/bin/bash
# getting swarm config
my_dir="$(dirname "$0")"
source "$my_dir/swarm-config"

# Can only run on manager nodes!
info() {
	docker node ls -q | xargs docker node inspect \
	  -f '{{ .ID }} [{{ .Description.Hostname }}]: {{ .Description.Platform }} {{ .Description.Resources }}
	  leader? {{ .ManagerStatus }}
	  {{ .Spec.Availability }}.{{ .Spec.Role }} {{ .Status.Addr }} {{ .Status.State }}
	  {{ .Spec.Labels }}
	  '
	  
	docker service ps $(docker service ls -q)
}

ssh $USER@$LEADER "$(declare -f info); info"
