#!/bin/bash

# flashing the img
HOSTNAME="pi-master"
# SSID="wifi-name"
# PASS="wifi-pass"
# Add these options if want wifi
# --ssid "$SSID" \
# --password "$PASS" \
# 
echo "Building #${HOSTNAME} ┌∩┐(◟‿◞◟‿◞)┌∩┐.."

./flash \
	--hostname "$HOSTNAME" \
	--als boot/als.sh \
	--bootconf boot/config.txt \
	--userdata boot/user-data \
	--dockercmd "docker swarm init" \
	$(ls | grep *.img.zip)


echo "#${HOSTNAME} (╯°□°)–︻╦╤─ – – –ready!"
