#!/bin/bash

# flashing the img
HOSTNAME="pi-master"
SSID="***REMOVED***"
PASS="***REMOVED***"

echo "Building #${HOSTNAME} ┌∩┐(◟‿◞◟‿◞)┌∩┐.."

./flash \
	--hostname "$HOSTNAME" \
	--ssid "$SSID" \
	--password "$PASS" \
	--als boot/als.sh \
	--bootconf boot/config.txt \
	--userdata boot/user-data \
	--dockercmd "docker swarm init" \
	$(ls | grep hypriotos.*.zip)

echo "#${HOSTNAME} (╯°□°)–︻╦╤─ – – –ready!"
