#!/bin/bash

# flashing the img
HOSTNAME="pi-master"
#SSID="wifi-name"
#PASS="wifi-pass"

echo "Building #${HOSTNAME} ┌∩┐(◟‿◞◟‿◞)┌∩┐.."

./flash \
	--hostname "$HOSTNAME" \
	--als boot/als.sh \
	--bootconf boot/config.txt \
	--userdata boot/user-data \
	# --ssid "$SSID" \
	# --password "$PASS" \
	--dockercmd "docker swarm init" \
	$(ls | grep *.img.zip)

echo "#${HOSTNAME} (╯°□°)–︻╦╤─ – – –ready!"
