#!/bin/bash

# flashing the img
HOSTNAME="pi-baker-${1:-0}"
TOKEN="${2}"
MASTER_ADD="${3}"

# SSID="wifi-name"
# PASS="wifi-pass"
# Add these options if want wifi
# --ssid "$SSID" \
# --password "$PASS" \

# if [ -z ${TOKEN} ]; then 
# 	echo "TOKEN is unset, run \`docker swarm join-token (worker|manager)\` from master node to generate new token"; 
# 	echo "it should look like \`SWMTKN-1-5nst1oa4hzvseuu69fs0p7k7v9ivlgijfg5plsx20spyqusizu-0o7aah0h696rpkha7zi05hojs\`"
# 	exit 1; 
# fi

# if [ -z ${MASTER_ADD} ]; then 
# 	echo "MASTER_ADD is unset"; 
# 	echo "it should look like \`swarm-master-ip:2377\`"
# 	exit 1; 
# fi

echo "Building #${HOSTNAME} (づ ￣ ³￣)づ ⓈⓂⓄⓄⓉⒽ"


./flash \
	--hostname "$HOSTNAME" \
	--als boot/als.sh \
	--bootconf boot/config.txt \
	--metadata boot/meta-data \
	--userdata boot/user-data \
	"$(ls | grep *.img.zip)"
	
	# --dockercmd "docker swarm join --token $TOKEN $MASTER_ADD" \

echo "#${HOSTNAME} (╯°□°)–︻╦╤─ – – –ready to join master ${MASTER_ADD}!"


