#!/bin/bash
#
# getting swarm config
my_dir="$(dirname "$0")"
source "$my_dir/swarm-config"

create_key() {
	local key_name="${1:-lucy}"
	echo "┌∩┐(◟‿◞◟‿◞)┌∩┐ gen key \`$key_name\` under .keys/"
	ssh-keygen -t rsa -b 4096 -f ".keys/$key_name"
}

add_key_to_host() {
	local key_name="${2:-lucy}"
	local f_host=$1
	local f_ip=`$my_dir/bin/getip $f_host`
	if [ -z $f_ip ]; then
		echo "$f_host not found.."
		return 1
	fi

	echo "adding key \`$key_name\` to $f_host @$f_ip"

	ssh-copy-id -i ".keys/$key_name" "$USER@$f_ip"
}
#
create_key
for node in "${formation[@]}"; do
	add_key_to_host "$node.local"
done
