#!/bin/bash

#https://github.com/moby/moby/issues/25432
hard_restart() {
	sudo service docker stop
	sudo rm -Rf /var/lib/docker/swarm
	sudo service docker start
}

#todo https://github.com/moby/moby/issues/25432#issuecomment-304639288
sort_restart() {
	# using systemd
	sudo systemctl stop docker
	
	# make sure to make a backup if you delete something wrong
	sudo cp -ar /var/lib/docker/swarm/ /tmp/swarm.bak
	
	sudo nano /var/lib/docker/swarm/state.json
	# state.json will look something like this:
	# [{"node_id":"nodeidofhealthynode","addr":"123.123.123.123:2377"},
	# {"node_id":"nodeidofunhealthynode","addr":"123.123.123.124:2377"}]
	
	# You want to delete any entries to unhealthy nodes. so just one healthy manager node is left
	# [{"node_id":"nodeidofhealthynode","addr":"123.123.123.123:2377"}]
	# sed .....
	# 
	# lastly restart docker
	sudo systemctl start docker
}
