#!/bin/bash
# Can only run on manager nodes!

docker node ls -q | xargs docker node inspect \
  -f '{{ .ID }} [{{ .Description.Hostname }}]: {{ .Description.Platform }} {{ .Description.Resources }}
  leader? {{ .ManagerStatus }}
  {{ .Spec.Availability }}.{{ .Spec.Role }} {{ .Status.Addr }} {{ .Status.State }}
  {{ .Spec.Labels }}
  '
